/*
 * ⚠️⚠️⚠️ THIS FILE WAS SCAFFOLDED BY `@grafana/create-plugin`. DO NOT EDIT THIS FILE DIRECTLY. ⚠️⚠️⚠️
 *
 * In order to extend the configuration follow the steps in
 * https://grafana.com/developers/plugin-tools/how-to-guides/extend-configurations#extend-the-eslint-config
 */

import { defineConfig } from 'eslint/config';
import { fixupPluginRules } from '@eslint/compat';
import grafanaConfig from '@grafana/eslint-config/flat.js';

const fixedGrafanaConfig = grafanaConfig.map((config) => {
  if (!config.plugins?.react) {
    return config;
  }

  return {
    ...config,
    plugins: {
      ...config.plugins,
      react: fixupPluginRules(config.plugins.react),
    },
  };
});

export default defineConfig([
  ...fixedGrafanaConfig,
  {
    rules: {
      'react/prop-types': 'off',
    },
  },
  {
    files: ['src/**/*.{ts,tsx}'],

    languageOptions: {
      parserOptions: {
        project: './tsconfig.json',
      },
    },

    rules: {
      '@typescript-eslint/no-deprecated': 'warn',
    },
  },
  {
    files: ['./tests/**/*'],

    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
]);
