"""Slack incoming webhook client for RCA completion notifications."""

import structlog
import httpx

from app.config import settings

logger = structlog.get_logger()

# Confidence level → emoji + colour
_CONFIDENCE_EMOJI: dict[str, str] = {
    "high": "🟢",
    "medium": "🟡",
    "low": "🔴",
}

_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🚨",
    "warning": "⚠️",
    "info": "ℹ️",
    "unknown": "❓",
}


async def send_slack_notification(
    rca_id: str,
    alert_name: str,
    service_name: str,
    environment: str,
    severity: str,
    confidence_level: str,
    root_cause: str,
    frontend_url: str,
) -> None:
    """Post an RCA completion notification to Slack.

    Sends a formatted Block Kit message to the configured Slack incoming
    webhook URL. Does nothing if SLACK_WEBHOOK_URL is not configured.

    Args:
        rca_id: UUID string of the completed RCA.
        alert_name: Name of the triggering alert.
        service_name: Name of the affected service.
        environment: Deployment environment.
        severity: Alert severity level.
        confidence_level: RCA confidence level (high/medium/low).
        root_cause: Brief root cause description (truncated for Slack).
        frontend_url: Base URL of the Orca frontend for the RCA link.

    Raises:
        httpx.HTTPStatusError: If the Slack webhook returns a non-2xx response.
    """
    if not settings.SLACK_WEBHOOK_URL:
        return

    log = logger.bind(rca_id=rca_id)

    confidence_emoji = _CONFIDENCE_EMOJI.get(confidence_level, "❓")
    severity_emoji = _SEVERITY_EMOJI.get(severity, "❓")

    rca_url = f"{frontend_url}/rca/{rca_id}"
    root_cause_short = root_cause[:300] + "..." if len(root_cause) > 300 else root_cause

    payload = {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{severity_emoji} RCA Complete: {alert_name}",
                    "emoji": True,
                },
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Service:*\n{service_name}",
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Environment:*\n{environment}",
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Severity:*\n{severity.upper()}",
                    },
                    {
                        "type": "mrkdwn",
                        "text": f"*Confidence:*\n{confidence_emoji} {confidence_level.upper()}",
                    },
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Root Cause:*\n{root_cause_short}",
                },
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "View Full RCA Report",
                            "emoji": True,
                        },
                        "url": rca_url,
                        "style": "primary",
                    }
                ],
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"RCA ID: `{rca_id}` | Generated by Orca 🐋",
                    }
                ],
            },
        ]
    }

    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.post(
            settings.SLACK_WEBHOOK_URL,
            json=payload,
            headers={"Content-Type": "application/json"},
        )
        response.raise_for_status()
        log.info("slack_notification_sent", status_code=response.status_code)

